#for account controller
getAccounts: /accounts
registerAccount: /accounts
verifyEmail: /verify-email
loginAccount: /login
editAccount: /accounts/{accountId}
accountConfigurations: /accounts/{accountId}/configurations
followAccount : /follow-account
unfollowAccount: /unfollow-account
#for post controller
getTweets: /tweets
getAccountTweets: /accounts/{accountId}/tweets
createTweet: /tweets
editTweet: /tweets/{tweetId}
deleteAccountTweet: /account/{accountId}/tweets/{tweetId}
retweetPost: /retweet
reactTweet: /react-tweet
configureTweet: /tweets/{tweetId}/configure
#for comment controller
createComment: /comments
getTweetComments: /tweets/{tweetId}/comments
editComment: /comments/{commentId}
deleteComment : /comments/{commentId}
reactComment: /react-comment
  
  