server.port: 8080
spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/twitter_clone
    username: lionel
    password: Mmh28803#
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
